version: "3.7"
services:
  trademark-db:
    container_name: trademark-db
    image: "postgres:14.6"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - trademark
    volumes:
      - pgdata:/var/lib/postgresql/data

  trademark-backend:
    image: "trademark-backend:latest"
    container_name: trademark-backend
    environment:
      PORT: 8080
      POSTGRES_DSN: postgres://trademark:trademark@trademark-db:5432/trademark
    depends_on:
      - trademark-db
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - trademark


networks:
  trademark:
    external: True


volumes:
  pgdata:
